//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xkeymacs.rc
//
#define IDS_DEFAULT                     1
#define IDS_DEFAULT_TITLE               2
#define IDS_DIALOG                      3
#define IDS_DIALOG_TITLE                4
#define IDS_KEYBOARD                    5
#define IDS_REG_ENTRY_USE_DIALOG_SETTING 10
#define IDS_REGISTRY_KEY                11
#define IDS_REG_SECTION_APPLICATION     12
#define IDS_REG_ENTRY_APPLICATION       13
#define IDS_REG_ENTRY_NONE              14
#define IDS_REG_ENTRY_CONTROL           15
#define IDS_REG_ENTRY_CONTROLX          16
#define IDS_REG_ENTRY_META              17
#define IDS_REG_SUB_KEY                 18
#define IDS_REGSUBKEY_DATA              18
#define IDS_REG_ENTRY_APPLICATOIN_TITLE 19
#define IDS_REGSUBKEY_AUTORUN           20
#define IDS_APPLICATION_LIST_ITEM       21
#define IDS_SEPARATE_CLASS_WINDOW       22
#define IDS_SEPARATE_WINDOWTITLE        23
#define IDS_REG_ENTRY_CONTROL_META      24
#define IDS_REG_ENTRY_CONTROL_META_SHIFT 24
#define IDS_REG_ENTRY_KILL_RING_MAX     25
#define IDS_REG_ENTRY_CONTROL_SHIFT     26
#define IDS_REG_ENTRY_META_SHIFT        27
#define IDS_REG_ENTRY_DISABLE_XKEYMACS  28
#define IDC_REG_ENTRY_IGNORE_META_CTRL  29
#define IDC_REG_ENTRY_IGNORE_C_X        30
#define IDS_ERR_SAVE_DATA               31
#define IDS_ERR_WINDOWS_VERSION         32
#define IDS_ERR_IMPORT                  33
#define IDS_ERR_EXPORT                  34
#define IDC_REG_ENTRY_ENABLE_CUA        35
#define IDS_REG_SECTION_ORIGINAL        36
#define IDS_REG_ORIGINAL_PREFIX         37
#define IDS_REG_ENTRY_WINDOW_TEXT       38
#define IDS_REG_ENTRY_WINDOW_TEXT_TYPE  39
#define IDS_REG_ENTRY_326_COMPATIBLE    40
#define IDS_PROCESS                     41
#define IDS_PROCESSID                   42
#define IDS_REGSUBKEY_PERF              43
#define IDS_REGSUBKEY_COUNTERS          44
#define IDS_UNKNOWN_TASK                45
#define IDS_IME_FILE_NAME               46
#define IDS_ERR_LOST_KEY                47
#define IDS_FOR_LOGGED_ON_USER          48
#define IDS_FOR_ANY_USER                49
#define IDS_FOR                         50
#define IDS_EXPLORER                    51
#define IDS_PROJECT                     52
#define IDS_EXCEL                       53
#define IDS_MSDN                        54
#define IDS_B2                          55
#define IDS_MSIMN                       56
#define IDS_UNKNOWN_APPLICATION         61
#define IDS_PROGRAM_MANAGER             62
#define IDS_EXTENSION_EXECUTABLE        63
#define IDS_BECKY                       64
#define IDS_OUTLOOK_EXPRESS             65
#define IDS_VISUAL_SOURCESAFE_EXPLORER  66
#define IDS_DISABLE                     71
#define IDS_ENABLE                      72
#define IDS_IMPORT                      73
#define IDS_EXPORT                      74
#define IDS_TIP_CX                      75
#define IDS_TIP_CTRL                    76
#define IDS_TIP_SHIFT                   77
#define IDS_TIP_ALT                     78
#define IDS_TIP_META                    79
#define IDS_REGISTRATION_FILTER         80
#define IDS_REGSUBKEY_KEYBOARD_LAYOUT   81
#define IDS_SCANCODE_MAP                82
#define IDS_REGSUBKEY_KEY_REMAP         83
#define IDS_0                           84
#define IDS_RESTART_OR_NOT              85
#define IDS_RESTART_CAPTION             86
#define IDS_REGSUBKEY_FILE_COMPLETION   87
#define IDS_COMPLETION_CHAR             88
#define IDS_REGSUBKEY_KEYBOARD_LAYOUT_ANY_USER 89
#define IDS_URL                         91
#define IDS_WINDOW_TEXT_IGNORE          91
#define IDS_WINDOW_TEXT_MATCH           92
#define IDS_WINDOW_TEXT_MATCH_FORWARD   93
#define IDS_WINDOW_TEXT_MATCH_BACKWARD  94
#define IDS_WINDOW_TEXT_MATCH_FULL      95
#define IDS_TIP_MX                      96
#define IDD_ABOUTBOX                    100
#define IDS_VER_SUB_BLOCK               101
#define IDR_MAINFRAME                   128
#define IDR_XKEYMATYPE                  129
#define IDR_RIGHT_MENU                  130
#define IDR_STOP                        130
#define IDR_MAIN_DISABLE_WOCQ           130
#define IDD_XKEYMACS                    131
#define IDD_OPTIONS                     132
#define IDI_CTRL_ON                     133
#define IDI_CTRL_OFF                    134
#define IDI_CX_ON                       135
#define IDI_CX_OFF                      136
#define IDC_HAND_CURSOR                 137
#define IDI_SHIFT_ON                    138
#define IDI_SHIFT_OFF                   139
#define IDI_ALT_ON                      140
#define IDI_ALT_OFF                     141
#define IDD_CUSTOMIZE                   142
#define IDI_META_ON                     143
#define IDI_META_OFF                    144
#define IDR_MAIN_DISABLE                145
#define IDD_104KEYBOARD                 145
#define IDD_109KEYBOARD                 146
#define IDC_DRAG_CURSOR                 146
#define IDR_MAIN_DISABLE_TMP            147
#define IDD_PROPERTIES                  148
#define IDI_MX_ON                       148
#define IDD_PROPERTIES_BASIC            149
#define IDI_MX_OFF                      149
#define IDD_PROPERTIES_ADVANCED         150
#define IDB_SORT_ASCENDING              150
#define IDD_PROPERTIES_LIST             151
#define IDB_SORT_DESCENDING             151
#define IDD_MACRO                       152
#define IDC_DISABLE_CURSOR              154
#define IDC_DISABLE_WOCQ_CURSOR         155
#define IDC_DISABLE_TMP_CURSOR          156
#define IDS_REG_ENTRY_ICON_META         255
#define IDS_REG_ENTRY_NONE_FOO          256
#define IDS_REG_ENTRY_NONE_SHIFT_FOO    257
#define IDS_REG_ENTRY_CONTROL_FOO       258
#define IDS_REG_ENTRY_CONTROL_SHIFT_FOO 259
#define IDS_REG_ENTRY_CONTROLX_FOO      260
#define IDS_REG_ENTRY_CONTROLX_SHIFT_FOO 261
#define IDS_REG_ENTRY_CONTROLX_CONTROL_FOO 262
#define IDS_REG_ENTRY_CONTROLX_CONTROL_SHIFT_FOO 263
#define IDS_REG_ENTRY_META_FOO          264
#define IDS_REG_ENTRY_META_SHIFT_FOO    265
#define IDS_DISABLED                    266
#define IDS_REG_ENTRY_CTRL              267
#define IDS_REG_ENTRY_CX                268
#define IDS_REG_ENTRY_MAIN              269
#define IDS_REG_ENTRY_SHIFT             270
#define IDS_REG_ENTRY_ALT               271
#define IDS_REG_ENTRY_ACCELERATE        272
#define IDS_REGSUBKEY_KEYBOARD          273
#define IDS_KEYBOARD_SPEED              274
#define IDS_REG_ENTRY_CHANGE_CURSOR     275
#define IDS_REG_ENTRY_AT_IBEAM_CURSOR_ONLY 276
#define IDS_REG_ENTRY_MX                277
#define IDS_FILES                       401
#define IDS_SEARCH                      402
#define IDS_WINDOW                      403
#define IDS_RECOVERY                    404
#define IDS_MOTION                      405
#define IDS_IME                         406
#define IDS_KILL                        407
#define IDS_OTHER                       408
#define IDS_ORIGINAL                    409
#define IDS_CATEGORY                    411
#define IDS_COMMAND                     412
#define IDS_KEY                         413
#define IDS_MODIFIER                    414
#define IDS_FSET                        451
#define IDS_README                      461
#define IDS_SET_MARK_COMMAND_D          500
#define IDS_BEGINNING_OF_LINE_D         501
#define IDS_BACKWARD_CHAR_D             502
#define IDS_DELETE_CHAR_D               503
#define IDS_END_OF_LINE_D               504
#define IDS_FORWARD_CHAR_D              505
#define IDS_KEYBOARD_QUIT_D             506
#define IDS_HELP_COMMAND_D              507
#define IDS_KILL_LINE_D                 508
#define IDS_RECENTER_D                  509
#define IDS_NEWLINE_D                   510
#define IDS_NEXT_LINE_D                 511
#define IDS_OPEN_LINE_D                 512
#define IDS_PREVIOUS_LINE_D             513
#define IDS_QUOTED_INSERT_D             514
#define IDS_ISEARCH_BACKWARD_D          515
#define IDS_ISEARCH_FORWARD_D           516
#define IDS_TRANSPOSE_CHARS_D           517
#define IDS_UNIVERSAL_ARGUMENT_D        518
#define IDS_SCROLL_UP_D                 519
#define IDS_KILL_REGION_D               520
#define IDS_CONTROL_X_PREFIX_D          521
#define IDS_YANK_D                      522
#define IDS_ICONIFY_OR_DEICONIFY_FRAME_D 523
#define IDS_QUAIL_MODE_D                524
#define IDS_UNDO_D                      525
#define IDS_TOGGLE_WIN32IME_MODE_D      526
#define IDS_BACKWARD_WORD_D             527
#define IDS_FORWARD_WORD_D              528
#define IDS_DIGIT_ARGUMENT_D            529
#define IDS_NEGATIVE_ARGUMENT_D         530
#define IDS_SAVE_BUFFERS_KILL_EMACS_D   531
#define IDS_FIND_FILE_D                 532
#define IDS_MARK_PAGE_D                 533
#define IDS_SAVE_BUFFER_D               534
#define IDS_WRITE_FILE_D                535
#define IDS_SHELL_COMMAND_D             536
#define IDS_BEGINNING_OF_BUFFER_D       537
#define IDS_END_OF_BUFFER_D             538
#define IDS_SCROLL_DOWN_D               539
#define IDS_KILL_RING_SAVE_D            540
#define IDS_BACKWARD_DELETE_CHAR_D      541
#define IDS_TAB_D                       542
#define IDS_META_PREFIX_D               543
#define IDS_META_D                      544
#define IDS_DIGIT_ARGUMENT0_D           545
#define IDS_DIGIT_ARGUMENT1_D           546
#define IDS_DIGIT_ARGUMENT2_D           547
#define IDS_DIGIT_ARGUMENT3_D           548
#define IDS_DIGIT_ARGUMENT4_D           549
#define IDS_DIGIT_ARGUMENT5_D           550
#define IDS_DIGIT_ARGUMENT6_D           551
#define IDS_DIGIT_ARGUMENT7_D           552
#define IDS_DIGIT_ARGUMENT8_D           553
#define IDS_DIGIT_ARGUMENT9_D           554
#define IDS_META_PREFIX_AND_ORIGINAL_D  555
#define IDS_KILL_BUFFER_D               556
#define IDS_KILL_WORD_D                 557
#define IDS_MARK_WHOLE_BUFFER_D         558
#define IDS_DELETE_BACKWARD_CHAR_D      559
#define IDS_QUERY_REPLACE_D             560
#define IDS_QUERY_REPLACE_REGEXP_D      561
#define IDS_YANK_POP_D                  562
#define IDS_CLOSE_INPUT_METHOD_D        563
#define IDS_ENABLE_OR_DISABLE_XKEYMACS_D 564
#define IDS_ENTER_D                     565
#define IDS_IGNORE_D                    566
#define IDS_OPEN_INPUT_METHOD_D         567
#define IDS_SELECT_ALL_D                568
#define IDS_CALL_LAST_KBD_MACRO_D       569
#define IDS_END_KBD_MACRO_D             570
#define IDS_START_KBD_MACRO_D           571
#define IDS_SWITCH_BETWEEN_INPUT_LOCALES_D 572
#define IDS_SWITCH_TO_BUFFER_D          573
#define IDS_CONTROL_D                   574
#define IDS_CONTROL_PREFIX_D            575
#define IDS_ESCAPE_D                    576
#define IDS_TILDE_D                     577
#define IDS_BACK_QUOTE_D                578
#define IDS_RESTORE_D                   579
#define IDS_MOVE_D                      580
#define IDS_SIZE_D                      581
#define IDS_MINIMIZE_D                  582
#define IDS_MAXIMIZE_D                  583
#define IDS_MAXIMIZE_VERTICALLY_D       584
#define IDS_MAXIMIZE_HORIZONTALLY_D     585
#define IDS_PASS_THROUGH_D              586
#define IDS_REDO_D                      587
#define IDS_TEMPORARILY_DISABLE_XKEYMACS_D 588
#define IDS_COPY_D                      589
#define IDS_PASTE_D                     590
#define IDS_CUT_D                       591
#define IDS_NEW_D                       592
#define IDS_PRINT_D                     593
#define IDS_FIND_D                      594
#define IDS_FIND_NEXT_D                 595
#define IDS_TRANSPOSE_LINES_D           596
#define IDS_KILL_LINE_FOR_ALL_FORMAT_D  597
#define IDS_BACKWARD_KILL_WORD_D        598
#define IDS_ENABLE_XKEYMACS_D           599
#define IDS_DISABLE_XKEYMACS_D          600
#define IDS_CAPS_LOCK_D                 601
#define IDS_COMPLETE_CLOSE_INPUT_METHOD_D 602
#define IDS_COMPLETE_TOGGLE_INPUT_METHOD_D 603
#define IDS_UNDERSCORE_D                604
#define IDS_ROLL_UP_UNROLL_D            605
#define IDS_RETOP_D                     606
#define IDS_OSMODIFIER_SHIFT_D          607
#define IDS_OSMODIFIER_SHIFT_REPEAT_D   608
#define IDS_OSMODIFIER_CTRL_D           609
#define IDS_OSMODIFIER_CTRL_REPEAT_D    610
#define IDS_OSMODIFIER_ALT_D            611
#define IDS_OSMODIFIER_ALT_REPEAT_D     612
#define IDS_CYCLE_ITEMS_D               613
#define IDS_CYCLE_ITEMS_INVERSELY_D     614
#define IDS_TRANSPOSE_WORDS_D           615
#define IDS_FILL_PARAGRAPH_D            616
#define IDS_DOWNCASE_WORD_D             617
#define IDS_UPCASE_WORD_D               618
#define IDS_CAPITALIZE_WORD_D           619
#define IDS_EXECUTE_EXTENDED_COMMAND_D  620
#define IDS_ESC                         701
#define IDS_1                           702
#define IDS_2                           703
#define IDS_3                           704
#define IDS_4                           705
#define IDS_5                           706
#define IDS_6                           707
#define IDS_7                           708
#define IDS_8                           709
#define IDS_9                           710
#define IDS_0_                          711
#define IDS_MINUS                       712
#define IDS_EQUAL                       713
#define IDS_BACKSPACE                   714
#define IDS_TAB                         715
#define IDS_Q                           716
#define IDS_W                           717
#define IDS_E                           718
#define IDS_R                           719
#define IDS_T                           720
#define IDS_Y                           721
#define IDS_U                           722
#define IDS_I                           723
#define IDS_O                           724
#define IDS_P                           725
#define IDS_SQUARE_BRA                  726
#define IDS_SQUARE_CKET                 727
#define IDS_ENTER                       728
#define IDS_NUMPADENTER                 729
#define IDS_LEFT_CTRL                   730
#define IDS_RIGHT_CTRL                  731
#define IDS_PAUSE                       732
#define IDS_A                           733
#define IDS_S                           734
#define IDS_D                           735
#define IDS_F                           736
#define IDS_G                           737
#define IDS_H                           738
#define IDS_J                           739
#define IDS_K                           740
#define IDS_L                           741
#define IDS_SEMICOLON                   742
#define IDS_QUOTE                       743
#define IDS_BACK_QUOTE                  744
#define IDS_LEFT_SHIFT                  745
#define IDS_BACKSLASH                   746
#define IDS_Z                           747
#define IDS_X                           748
#define IDS_C                           749
#define IDS_V                           750
#define IDS_B                           751
#define IDS_N                           752
#define IDS_M                           753
#define IDS_COMMA                       754
#define IDS_PERIOD                      755
#define IDS_SLASH                       756
#define IDS_DIVIDE                      757
#define IDS_RIGHT_SHIFT                 758
#define IDS_MULTIPLY                    759
#define IDS_PRINT_SCREEN                760
#define IDS_LEFT_ALT                    761
#define IDS_RIGHT_ALT                   762
#define IDS_SPACE                       763
#define IDS_CAPS_LOCK                   764
#define IDS_F1                          765
#define IDS_F2                          766
#define IDS_F3                          767
#define IDS_F4                          768
#define IDS_F5                          769
#define IDS_F6                          770
#define IDS_F7                          771
#define IDS_F8                          772
#define IDS_F9                          773
#define IDS_F10                         774
#define IDS_NUM_LOCK                    775
#define IDS_SCROLL_LOCK                 776
#define IDS_NUMPAD7                     777
#define IDS_HOME                        778
#define IDS_NUMPAD8                     779
#define IDS_UP                          780
#define IDS_NUMPAD9                     781
#define IDS_PAGE_UP                     782
#define IDS_SUBTRACT                    783
#define IDS_NUMPAD4                     784
#define IDS_LEFT                        785
#define IDS_NUMPAD5                     786
#define IDS_NUMPAD6                     787
#define IDS_RIGHT                       788
#define IDS_ADD                         789
#define IDS_NUMPAD1                     790
#define IDS_END                         791
#define IDS_NUMPAD2                     792
#define IDS_DOWN                        793
#define IDS_NUMPAD3                     794
#define IDS_PAGE_DOWN                   795
#define IDS_NUMPAD0                     796
#define IDS_INSERT                      797
#define IDS_NUMPADDELETE                798
#define IDS_DELETE                      799
#define IDS_F11                         800
#define IDS_F12                         801
#define IDS_LEFT_WINDOWS                802
#define IDS_RIGHT_WINDOWS               803
#define IDS_APPLICATION                 804
#define IDS_KANA                        805
#define IDS_BACKSLASH2                  806
#define IDS_CONVERT                     807
#define IDS_NONCONVERT                  808
#define IDS_BACKSLASH1                  809
#define IDS_CARET                       810
#define IDS_AT_MARK                     811
#define IDS_COLON                       812
#define IDS_HANKAKU                     813
#define IDS_ACPI_POWER                  814
#define IDS_ACPI_SLEEP                  815
#define IDS_ACPI_WAKE                   816
#define IDS_CONTROL_X_PREFIX_T          900
#define IDS_CONTROL_T                   901
#define IDS_CONTROL_PREFIX_T            902
#define IDS_CLOSE_INPUT_METHOD_T        903
#define IDS_COPY_T                      904
#define IDS_CUT_T                       905
#define IDS_ENABLE_OR_DISABLE_XKEYMACS_T 906
#define IDS_ENTER_T                     907
#define IDS_NEWLINE_T                   907
#define IDS_ESCAPE_T                    908
#define IDS_FIND_T                      909
#define IDS_FIND_NEXT_T                 910
#define IDS_IGNORE_T                    911
#define IDS_KILL_LINE_FOR_ALL_FORMAT_T  912
#define IDS_MAXIMIZE_T                  913
#define IDS_MAXIMIZE_HORIZONTALLY_T     914
#define IDS_MAXIMIZE_VERTICALLY_T       915
#define IDS_META_PREFIX_T               916
#define IDS_META_T                      917
#define IDS_META_PREFIX_AND_ORIGINAL_T  918
#define IDS_MINIMIZE_T                  919
#define IDS_MOVE_T                      920
#define IDS_NEW_T                       921
#define IDS_OPEN_INPUT_METHOD_T         922
#define IDS_PASS_THROUGH_T              923
#define IDS_PASTE_T                     924
#define IDS_PRINT_T                     925
#define IDS_REDO_T                      926
#define IDS_RESTORE_T                   927
#define IDS_SELECT_ALL_T                928
#define IDS_SIZE_T                      929
#define IDS_SWITCH_BETWEEN_INPUT_LOCALES_T 930
#define IDS_TEMPORARILY_DISABLE_XKEYMACS_T 931
#define IDS_TILDE_T                     932
#define IDS_BACK_QUOTE_T                933
#define IDS_BACKWARD_CHAR_T             934
#define IDS_BACKWARD_WORD_T             935
#define IDS_BEGINNING_OF_BUFFER_T       936
#define IDS_BEGINNING_OF_LINE_T         937
#define IDS_CALL_LAST_KBD_MACRO_T       938
#define IDS_DELETE_BACKWARD_CHAR_T      939
#define IDS_DELETE_CHAR_T               940
#define IDS_END_KBD_MACRO_T             941
#define IDS_END_OF_BUFFER_T             942
#define IDS_END_OF_LINE_T               943
#define IDS_FIND_FILE_T                 944
#define IDS_FORWARD_CHAR_T              945
#define IDS_FORWARD_WORD_T              946
#define IDS_ICONIFY_OR_DEICONIFY_FRAME_T 947
#define IDS_ISEARCH_BACKWARD_T          948
#define IDS_ISEARCH_FORWARD_T           949
#define IDS_KEYBOARD_QUIT_T             950
#define IDS_KILL_BUFFER_T               951
#define IDS_KILL_LINE_T                 952
#define IDS_KILL_REGION_T               953
#define IDS_KILL_RING_SAVE_T            954
#define IDS_KILL_WORD_T                 955
#define IDS_MARK_PAGE_T                 956
#define IDS_MARK_WHOLE_BUFFER_T         957
#define IDS_NEXT_LINE_T                 958
#define IDS_DIGIT_ARGUMENT0_T           959
#define IDS_DIGIT_ARGUMENT1_T           960
#define IDS_DIGIT_ARGUMENT2_T           961
#define IDS_DIGIT_ARGUMENT3_T           962
#define IDS_DIGIT_ARGUMENT4_T           963
#define IDS_DIGIT_ARGUMENT5_T           964
#define IDS_DIGIT_ARGUMENT6_T           965
#define IDS_DIGIT_ARGUMENT7_T           966
#define IDS_DIGIT_ARGUMENT8_T           967
#define IDS_DIGIT_ARGUMENT9_T           968
#define IDS_NEGATIVE_ARGUMENT_T         969
#define IDS_OPEN_LINE_T                 970
#define IDS_PREVIOUS_LINE_T             971
#define IDS_QUERY_REPLACE_T             972
#define IDS_QUERY_REPLACE_REGEXP_T      973
#define IDS_RECENTER_T                  974
#define IDS_SAVE_BUFFER_T               975
#define IDS_SAVE_BUFFERS_KILL_EMACS_T   976
#define IDS_SCROLL_DOWN_T               977
#define IDS_SCROLL_UP_T                 978
#define IDS_SET_MARK_COMMAND_T          979
#define IDS_SHELL_COMMAND_T             980
#define IDS_START_KBD_MACRO_T           981
#define IDS_SWITCH_TO_BUFFER_T          982
#define IDS_TAB_T                       983
#define IDS_TOGGLE_WIN32IME_MODE_T      984
#define IDS_TRANSPOSE_CHARS_T           985
#define IDS_TRANSPOSE_LINES_T           986
#define IDS_UNDO_T                      987
#define IDS_UNIVERSAL_ARGUMENT_T        988
#define IDS_WRITE_FILE_T                989
#define IDS_YANK_T                      990
#define IDS_YANK_POP_T                  991
#define IDS_BACKWARD_KILL_WORD_T        992
#define IDS_ENABLE_XKEYMACS_T           993
#define IDS_DISABLE_XKEYMACS_T          994
#define IDS_CAPS_LOCK_T                 995
#define IDS_COMPLETE_CLOSE_INPUT_METHOD_T 996
#define IDS_COMPLETE_TOGGLE_INPUT_METHOD_T 997
#define IDS_UNDERSCORE_T                998
#define IDS_ROLL_UP_UNROLL_T            999
#define IDC_APPLY                       1000
#define IDS_RETOP_T                     1000
#define IDC_LOAD_DEFAULT                1001
#define IDS_OSMODIFIER_SHIFT_T          1001
#define IDC_SELECT_ALL                  1002
#define IDS_OSMODIFIER_SHIFT_REPEAT_T   1002
#define IDC_CLEAR_ALL                   1003
#define IDS_OSMODIFIER_CTRL_T           1003
#define IDC_APPLICATION                 1004
#define IDS_OSMODIFIER_CTRL_REPEAT_T    1004
#define IDC_CP                          1005
#define IDC_APPLICATION_                1005
#define IDS_OSMODIFIER_ALT_T            1005
#define IDC_CN                          1006
#define IDS_OSMODIFIER_ALT_REPEAT_T     1006
#define IDC_CF                          1007
#define IDS_CYCLE_ITEMS_T               1007
#define IDC_CB                          1008
#define IDS_CYCLE_ITEMS_INVERSELY_T     1008
#define IDC_CA                          1009
#define IDS_TRANSPOSE_WORDS_T           1009
#define IDC_CE                          1010
#define IDS_FILL_PARAGRAPH_T            1010
#define IDC_CV                          1011
#define IDS_DOWNCASE_WORD_T             1011
#define IDC_MV                          1012
#define IDS_UPCASE_WORD_T               1012
#define IDC_CD                          1013
#define IDS_CAPITALIZE_WORD_T           1013
#define IDC_CH                          1014
#define IDS_EXECUTE_EXTENDED_COMMAND_T  1014
#define IDC_CW                          1015
#define IDC_MW                          1016
#define IDC_CY                          1017
#define IDC_CT                          1018
#define IDC_CK                          1019
#define IDC_CSPACE                      1020
#define IDC_CI                          1021
#define IDC_CM                          1022
#define IDC_CG                          1023
#define IDC_CDIGIT                      1024
#define IDC_CSLASH                      1025
#define IDC_CS                          1026
#define IDC_CXCJ                        1027
#define IDC_CXCC                        1028
#define IDC_CXCF                        1029
#define IDC_CXCS                        1030
#define IDC_CXCW                        1031
#define IDC_CXU                         1032
#define IDC_CZ                          1033
#define IDC_USE_DEFAULT                 1034
#define IDC_MT                          1034
#define IDC_CO                          1035
#define IDC_CBACKSLASH                  1036
#define IDC_CBACKSLASH_106              1038
#define IDC_AUTO_RUN                    1039
#define IDC_CL                          1040
#define IDC_CR                          1042
#define IDC_MS1                         1043
#define IDC_SQUARE_BRA                  1046
#define IDC_ESCAPE                      1047
#define IDC_SQUARE_BRA_                 1047
#define IDC_MSPERIOD                    1048
#define IDC_MSCOMMA                     1049
#define IDC_CXCP                        1052
#define IDC_MB                          1053
#define IDC_MF                          1054
#define IDC_REMAP_CAPSLOCK_LEFTCTRL     1058
#define IDC_REMAP_LEFTCTRL_CAPSLOCK     1059
#define IDC_SWAP_ESC_BACKQUOTE          1060
#define IDC_USAGE                       1061
#define IDC_FILE_COMPLETION             1063
#define IDC_VERSION_INFORMATION         1064
#define IDC_LEFT_ALT                    1065
#define IDC_RIGHT_ALT                   1066
#define IDC_SPACE                       1067
#define IDC_LEFT_ALT_                   1068
#define IDC_ALT                         1069
#define IDC_SPACE_                      1069
#define IDC_RIGHT_ALT_                  1070
#define IDC_URL                         1071
#define IDC_CQ                          1073
#define IDC_C_X_                        1075
#define IDC_CTRL                        1076
#define IDC_SHIFT                       1077
#define IDC_M_X                         1078
#define IDC_CU                          1081
#define IDC_MS5                         1085
#define IDC_CMS5                        1086
#define IDC_MY                          1088
#define IDC_EDIT1                       1091
#define IDC_KILL_RING_MAX               1091
#define IDC_NEW_KEY                     1091
#define IDC_MACRO_NAME                  1091
#define IDC_REMAP_LWINDOWS_LALT         1092
#define IDC_REMAP_LEFTWINDOWS_LEFTALT   1092
#define IDC_REMAP_LALT_LWINDOWS         1093
#define IDC_REMAP_LEFTALT_LEFTWINDOWS   1093
#define IDC_REMAP_RWINDOWS_RALT         1094
#define IDC_REMAP_RIGHTWINDOWS_RIGHTALT 1094
#define IDC_REMAP_RALT_RWINDOWS         1095
#define IDC_REMAP_RIGHTALT_RIGHTWINDOWS 1095
#define IDC_REMAP_NONCONVERT_LALT       1096
#define IDC_REMAP_NONCONVERT_LEFTALT    1096
#define IDC_REMAP_CONVERT_LALT          1097
#define IDC_REMAP_CONVERT_LEFTALT       1097
#define IDC_RCTRL_LALT                  1098
#define IDC_REMAP_RIGHTCTRL_LEFTALT     1098
#define IDC_CENTER                      1099
#define IDC_C_                          1100
#define IDC_CO2                         1102
#define IDC_MI                          1106
#define IDC_CATEGORY                    1108
#define IDC_DESCRIPTION                 1111
#define IDC_COMMANDS                    1113
#define IDC_CURRENT_KEYS                1114
#define IDC_ASSIGN                      1115
#define IDC_REMOVE                      1116
#define IDC_RESET_ALL                   1117
#define IDC_SETTING_DEFAULT             1118
#define IDC_SETTING_SPECIFIC            1119
#define IDC_SETTING_DISABLE             1120
#define IDC_FILES                       1128
#define IDC_SEARCH                      1129
#define IDC_WINDOW                      1130
#define IDC_RECOVERY                    1131
#define IDC_MOTION                      1132
#define IDC_IME                         1133
#define IDC_KILL                        1134
#define IDC_OTHER                       1135
#define IDC_CURRENTLY_ASSIGNED          1136
#define IDC_M_                          1137
#define IDC_KANA_                       1138
#define IDC_CXK                         1139
#define IDC_CONVERT_                    1139
#define IDC_MD                          1141
#define IDC_CXH                         1143
#define IDC_USE_DIALOG_SETTING          1148
#define IDC_CHECK1                      1149
#define IDC_CXS9                        1149
#define IDC_C_X                         1149
#define IDC_EXTENDED_KEY                1149
#define IDC_CHECK2                      1150
#define IDC_CXS0                        1150
#define IDC_REPEATED_KEY                1150
#define IDC_ENABLE_CUA                  1150
#define IDC_CXE                         1151
#define IDC_CXB                         1152
#define IDC_BACK_QUOTE                  1154
#define IDC_1                           1155
#define IDC_2                           1156
#define IDC_3                           1157
#define IDC_4                           1158
#define IDC_5                           1159
#define IDC_6                           1160
#define IDC_7                           1161
#define IDC_8                           1162
#define IDC_9                           1163
#define IDC_0                           1164
#define IDC_MINUS                       1165
#define IDC_EQUAL                       1166
#define IDC_BACKSPACE                   1167
#define IDC_TAB                         1168
#define IDC_LEFT_CTRL                   1169
#define IDC_ESC                         1170
#define IDC_CAPS_LOCK                   1171
#define IDC_F1                          1172
#define IDC_F2                          1173
#define IDC_LEFT_SHIFT                  1174
#define IDC_F3                          1175
#define IDC_Q                           1176
#define IDC_W                           1177
#define IDC_E                           1178
#define IDC_R                           1179
#define IDC_T                           1180
#define IDC_Y                           1181
#define IDC_U                           1182
#define IDC_I                           1183
#define IDC_O                           1184
#define IDC_P                           1185
#define IDC_CAPS_LOCK_                  1186
#define IDC_SQUARE_CKET                 1187
#define IDC_BACKSLASH                   1188
#define IDC_A                           1189
#define IDC_S                           1190
#define IDC_D                           1191
#define IDC_F                           1192
#define IDC_G                           1193
#define IDC_H                           1194
#define IDC_J                           1195
#define IDC_K                           1196
#define IDC_L                           1197
#define IDC_SEMICOLON                   1198
#define IDC_QUOTE                       1199
#define IDC_ENTER                       1200
#define IDC_Z                           1201
#define IDC_X                           1202
#define IDC_C                           1203
#define IDC_V                           1204
#define IDC_B                           1205
#define IDC_N                           1206
#define IDC_M                           1207
#define IDC_COMMA                       1208
#define IDC_PERIOD                      1209
#define IDC_SLASH                       1210
#define IDC_RIGHT_SHIFT                 1211
#define IDC_RIGHT_CTRL                  1212
#define IDC_LEFT_WINDOWS                1213
#define IDC_F4                          1214
#define IDC_F5                          1215
#define IDC_RIGHT_WINDOWS               1216
#define IDC_F6                          1217
#define IDC_F7                          1218
#define IDC_F8                          1219
#define IDC_F9                          1220
#define IDC_F10                         1221
#define IDC_F11                         1222
#define IDC_F12                         1223
#define IDC_INSERT                      1224
#define IDC_HOME                        1225
#define IDC_PAGE_UP                     1226
#define IDC_DELETE                      1227
#define IDC_END                         1228
#define IDC_PAGE_DOWN                   1229
#define IDC_UP                          1230
#define IDC_LEFT                        1231
#define IDC_DOWN                        1232
#define IDC_RIGHT                       1233
#define IDC_PRINT_SCREEN                1234
#define IDC_SCROLL_LOCK                 1235
#define IDC_PAUSE                       1236
#define IDC_NUM_LOCK                    1237
#define IDC_DIVIDE                      1238
#define IDC_MULTIPLY                    1239
#define IDC_SUBTRACT                    1240
#define IDC_NUMPAD7                     1241
#define IDC_NUMPAD8                     1242
#define IDC_NUMPAD9                     1243
#define IDC_NUMPAD4                     1244
#define IDC_NUMPAD5                     1245
#define IDC_NUMPAD6                     1246
#define IDC_NUMPAD1                     1247
#define IDC_NUMPAD2                     1248
#define IDC_NUMPAD3                     1249
#define IDC_NUMPAD0                     1250
#define IDC_ADD                         1251
#define IDC_NUMPADDELETE                1252
#define IDC_NUMPADENTER                 1253
#define IDC_ESC_                        1254
#define IDC_F1_                         1255
#define IDC_F2_                         1256
#define IDC_F3_                         1257
#define IDC_F4_                         1258
#define IDC_F5_                         1259
#define IDC_F6_                         1260
#define IDC_F7_                         1261
#define IDC_F8_                         1262
#define IDC_F9_                         1263
#define IDC_F10_                        1264
#define IDC_F11_                        1265
#define IDC_F12_                        1266
#define IDC_PRINT_SCREEN_               1267
#define IDC_SCROLL_LOCK_                1268
#define IDC_PAUSE_                      1269
#define IDC_BACK_QUOTE_                 1270
#define IDC_1_                          1271
#define IDC_2_                          1272
#define IDC_3_                          1273
#define IDC_4_                          1274
#define IDC_5_                          1275
#define IDC_6_                          1276
#define IDC_7_                          1277
#define IDC_8_                          1278
#define IDC_9_                          1279
#define IDC_0_                          1280
#define IDC_MINUS_                      1281
#define IDC_EQUAL_                      1282
#define IDC_BACKSPACE_                  1283
#define IDC_TAB_                        1284
#define IDC_Q_                          1285
#define IDC_W_                          1286
#define IDC_E_                          1287
#define IDC_R_                          1288
#define IDC_T_                          1289
#define IDC_Y_                          1290
#define IDC_U_                          1291
#define IDC_I_                          1292
#define IDC_O_                          1293
#define IDC_P_                          1294
#define IDC_SQUARE_CKET_                1295
#define IDC_BACKSLASH_                  1296
#define IDC_A_                          1297
#define IDC_S_                          1298
#define IDC_D_                          1299
#define IDC_F_                          1300
#define IDC_G_                          1301
#define IDC_H_                          1302
#define IDC_J_                          1303
#define IDC_K_                          1304
#define IDC_L_                          1305
#define IDC_SEMICOLON_                  1306
#define IDC_QUOTE_                      1307
#define IDC_ENTER_                      1308
#define IDC_LEFT_SHIFT_                 1309
#define IDC_Z_                          1310
#define IDC_X_                          1311
#define IDC_NONCONVERT                  1312
#define IDC_V_                          1313
#define IDC_B_                          1314
#define IDC_N_                          1315
#define IDC_CXCT                        1315
#define IDC_BACKSLASH1                  1316
#define IDC_COMMA_                      1317
#define IDC_PROPERTIES_LIST             1317
#define IDC_PERIOD_                     1318
#define IDC_SUBSEQUENT_KEYBOARD_INPUT   1318
#define IDC_SLASH_                      1319
#define IDC_RIGHT_SHIFT_                1320
#define IDC_NCODE                       1320
#define IDC_LEFT_CTRL_                  1321
#define IDC_WPARAM                      1321
#define IDC_LEFT_WINDOWS_               1322
#define IDC_LPARAM                      1322
#define IDC_RIGHT_WINDOWS_              1323
#define IDC_RIGHT_CTRL_                 1324
#define IDC_EDIT                        1324
#define IDC_INSERT_                     1325
#define IDC_HOME_                       1326
#define IDC_PAGE_UP_                    1327
#define IDC_MACRO_NAMES                 1327
#define IDC_DELETE_                     1328
#define IDC_SAVE                        1328
#define IDC_END_                        1329
#define IDC_KEY                         1329
#define IDC_PAGE_DOWN_                  1330
#define IDC_STATE                       1330
#define IDC_UP_                         1331
#define IDC_RADIO1                      1331
#define IDC_LEFT_                       1332
#define IDC_DOWN_                       1333
#define IDC_MDEL                        1333
#define IDC_RIGHT_                      1334
#define IDC_MF12                        1334
#define IDC_NUM_LOCK_                   1335
#define IDC_WINDOW_TEXT                 1335
#define IDC_DIVIDE_                     1336
#define IDC_MULTIPLY_                   1337
#define IDC_LEGAL_COPYRIGHT             1337
#define IDC_SUBTRACT_                   1338
#define IDC_ML                          1338
#define IDC_NUMPAD7_                    1339
#define IDC_MU                          1339
#define IDC_NUMPAD8_                    1340
#define IDC_MC                          1340
#define IDC_NUMPAD9_                    1341
#define IDC_MX                          1341
#define IDC_NUMPAD4_                    1342
#define IDC_NUMPAD5_                    1343
#define IDC_NUMPAD6_                    1344
#define IDC_ADD_                        1345
#define IDC_NUMPAD1_                    1346
#define IDC_NUMPAD2_                    1347
#define IDC_NUMPAD3_                    1348
#define IDC_NUMPAD0_                    1349
#define IDC_NUMPADDELETE_               1350
#define IDC_NUMPADENTER_                1351
#define IDC_BACKSLASH1_                 1352
#define IDC_BACKSLASH2                  1353
#define IDC_BACKSLASH2_                 1354
#define IDC_KANA                        1355
#define IDC_CONVERT                     1356
#define IDC_NONCONVERT_                 1357
#define IDC_ACPI_POWER                  1358
#define IDC_ACPI_POWER_                 1359
#define IDC_ACPI_SLEEP                  1360
#define IDC_ACPI_SLEEP_                 1361
#define IDC_ACPI_WAKE                   1362
#define IDC_ACPI_WAKE_                  1363
#define IDC_ABOUT                       32771
#define IDC_QUIT                        32772
#define IDC_STOP                        32773
#define IDC_DISABLE                     32773
#define IDC_PROPERTIES                  32774
#define IDC_OPTIONS                     32775
#define IDC_CUSTOMIZE                   32776
#define IDC_KEYBOARD                    32777
#define IDC_EXPORT                      32778
#define IDC_IMPORT                      32779
#define IDC_MACRO                       32780
#define IDC_RESET                       32781
#define IDC_KEYBOARD_ANY_USER           32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1342
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
